// 学習用のサンプル（titleEn・noteEn・groupEn は英語の画面用）。画面のボタンとsamples/qr/のQR画像の元になる（判定の結果はtest/samples.test.jsが確かめる）
// ドメインは、例示用に予約された.example・example.comを使う（実在のサイトを指さない）。
// TLDや無料ホスティングの例だけは実在のTLD・サービス名を使うが、ホスト名は架空のもの
(function (root) {
  "use strict";
  root.QRSamples = [
    {
      group: "偽物を本物に見せる",
      groupEn: "Making a fake look genuine",
      items: [
        { id: "fake-official", title: "公式ドメインを前に置く", url: "https://paypal.com.secure-login.example/verify",
          note: "paypal.comはサブドメインの飾り。持ち主はsecure-login.example", expect: "high", signal: "fake-official", qr: 1,
          titleEn: "Official domain in front", noteEn: "paypal.com is subdomain decoration. The owner is secure-login.example" },
        { id: "lookalike", title: "数字の0で似せる", url: "https://amaz0n.example/signin",
          note: "amaz0nの0は数字。公式によく似た名前", expect: "high", signal: "lookalike",
          titleEn: "Digit 0 as a look-alike", noteEn: "The 0 in amaz0n is a digit. A name close to the official one" },
        { id: "userinfo", title: "@の前に本物の名前", url: "https://www.amazon.co.jp@login-check.example/",
          note: "@より前は飾り。行き先はlogin-check.example", expect: "high", signal: "userinfo", qr: 2,
          titleEn: "Genuine name before the @", noteEn: "Everything before the @ is decoration. The destination is login-check.example" },
        { id: "homograph", title: "キリル文字で似せる", url: "https://аpple.example/",
          note: "先頭の「а」はキリル文字。見た目はapple", expect: "high", signal: "idn-mixed", qr: 3,
          titleEn: "Cyrillic look-alike", noteEn: "The first letter is Cyrillic. It looks like apple" },
        { id: "fake-path", title: "パスに公式ドメイン", url: "https://shop-news.example/vpass.ne.jp/login/",
          note: "国内の偽サイトに多い形。パスのvpass.ne.jpは飾り", expect: "high", signal: "fake-official",
          titleEn: "Official domain in the path", noteEn: "Common in fake sites targeting Japan. vpass.ne.jp in the path is decoration" },
        { id: "hosting", title: "無料ホスティングにブランド名", url: "https://eki-net-login.pages.dev/",
          note: "pages.devは誰でもサブドメインを作れる。持ち主は作った人", expect: "high", signal: "hosting", qr: 4,
          titleEn: "Brand name on free hosting", noteEn: "Anyone can create subdomains on pages.dev. The owner is whoever created it" },
      ],
    },
    {
      group: "使い捨てのドメイン",
      groupEn: "Throwaway domains",
      items: [
        { id: "random", title: "無作為な文字列のドメイン", url: "https://vzqxkwtr.top/jp/",
          note: "名前に意味がない。JPCERT/CCの2026年5月分の37.4%に出た、最も多い兆候", expect: "high", signal: "random-label", qr: 5,
          titleEn: "Random-string domain", noteEn: "A meaningless name. The most common sign: 37.4% of JPCERT/CC's May 2026 URLs" },
        { id: "bait-domain", title: "ドメイン名にsecure・account", url: "https://secure-account-update.example/",
          note: "それらしい語を並べたドメイン", expect: "high", signal: "bait-domain",
          titleEn: "secure and account in the domain name", noteEn: "A domain made of plausible words" },
      ],
    },
    {
      group: "見えない文字",
      groupEn: "Invisible characters",
      items: [
        { id: "rlo", title: "向きを変える文字（RLO）", url: "https://files.example/invoice\u202Efdp.exe",
          note: "見た目はinvoiceexe.pdf。実際は.exeで終わる", expect: "high", signal: "bidi", qr: 12,
          titleEn: "Direction-changing character (RLO)", noteEn: "Looks like invoiceexe.pdf, but actually ends with .exe" },
        { id: "zwsp", title: "見えない文字（ゼロ幅スペース）", url: "https://login\u200B-check.example/",
          note: "見た目はlogin-check.example。ホスト名では消えるが、中身には入っている", expect: "high", signal: "invisible", qr: 13,
          titleEn: "Invisible character (zero-width space)", noteEn: "Looks like login-check.example. It vanishes from the host name but is in the content" },
      ],
    },
    {
      group: "行き先を隠す",
      groupEn: "Hiding the destination",
      items: [
        { id: "ip", title: "10進数で書いたIPアドレス", url: "http://3232235777/login",
          note: "3232235777は192.168.1.1の別の書き方", expect: "high", signal: "ip-host",
          titleEn: "IP address written in decimal", noteEn: "3232235777 is another way to write 192.168.1.1" },
        { id: "shortener", title: "短縮URL", url: "https://bit.ly/3xY9Abc",
          note: "行き先が見えない。ただし短縮URLだけでは「中」にしない", expect: "low", signal: "shortener", qr: 6,
          titleEn: "Shortened URL", noteEn: "The destination is hidden, but a shortener alone does not make it Medium" },
        { id: "redirect", title: "URLの中に別のURL", url: "https://example.com/redirect?url=https://login-check.example/",
          note: "転送先を調べるボタンで、埋め込まれたURLも判定できる", expect: "low", signal: "embedded-url",
          titleEn: "A URL inside a URL", noteEn: "The button next to the sign lets you check the embedded URL too" },
        { id: "base64", title: "Base64で隠した行き先", url: "https://example.com/track?data=aHR0cHM6Ly9sb2dpbi1jaGVjay5leGFtcGxlLw",
          note: "戻すとhttps://login-check.example/", expect: "low", signal: "base64",
          titleEn: "Destination hidden in Base64", noteEn: "Decodes to https://login-check.example/" },
        { id: "download", title: "二重の拡張子のファイル", url: "https://files.example/invoice.pdf.exe",
          note: "最後の拡張子は.exe。開くとファイルが落ちてくる", expect: "low", signal: "download",
          titleEn: "Double file extension", noteEn: "The last extension is .exe. Opening it downloads a file" },
      ],
    },
    {
      group: "URLではないもの",
      groupEn: "Not a URL",
      items: [
        { id: "javascript", title: "javascript:スキーム", url: "javascript:alert('QR Risk Radar')",
          note: "開くとその場でスクリプトが動く", expect: "high", signal: "danger-scheme", qr: 7,
          titleEn: "javascript: scheme", noteEn: "Opening it runs a script on the spot" },
        { id: "data", title: "data:スキーム", url: "data:text/html,<h1>QR Risk Radar</h1>",
          note: "URLの中にHTMLをそのまま入れる", expect: "high", signal: "danger-scheme",
          titleEn: "data: scheme", noteEn: "Puts HTML directly inside the URL" },
        { id: "wifi", title: "暗号化なしのWi-Fi", url: "WIFI:T:nopass;S:Free-Cafe-WiFi;;",
          note: "通信を周りに見られるおそれ。店の掲示と同じ名前か確かめる", expect: "low", signal: "other-scheme", qr: 8,
          titleEn: "Unencrypted Wi-Fi", noteEn: "Others may see your traffic. Check the name against the shop's sign" },
        { id: "otp", title: "2段階認証の鍵", url: "otpauth://totp/Example:alice@example.com?secret=JBSWY3DPEHPK3PXP&issuer=Example",
          note: "撮られると同じ確認コードを作られる。秘密鍵は伏せて表示", expect: "low", signal: "other-scheme", qr: 10,
          titleEn: "Two-factor authentication key", noteEn: "A photo of it lets others make the same codes. The secret is masked" },
        { id: "sms", title: "本文にURLがあるSMS", url: "SMSTO:+81-90-0000-0000:Your parcel could not be delivered. Reschedule: https://sagawa-redelivery.example/",
          note: "宛先と本文、本文のURLの行き先を確かめる", expect: "low", signal: "other-scheme", qr: 11,
          titleEn: "SMS with a URL in the message", noteEn: "Check the recipient, the message, and where its URL leads" },
        { id: "contact", title: "有料番号とURLの連絡先", url: "MECARD:N:Support,Center;TEL:0570-000-000;URL:https://support-center.example/;;",
          note: "0570は通話料のかかる番号。登録する前に確かめる", expect: "low", signal: "other-scheme",
          titleEn: "Contact with a paid number and URL", noteEn: "0570 is a number the caller pays for. Check before saving" },
      ],
    },
    {
      group: "本物（比べるため）",
      groupEn: "Genuine (for comparison)",
      items: [
        { id: "official", title: "Amazonの公式のログイン", url: "https://www.amazon.co.jp/ap/signin",
          note: "登録ドメインはamazon.co.jp", expect: "low", signal: "official", qr: 9,
          titleEn: "Amazon's official login", noteEn: "The registrable domain is amazon.co.jp" },
        { id: "official-jp", title: "日本郵便の公式", url: "https://www.post.japanpost.jp/",
          note: "登録ドメインはjapanpost.jp", expect: "low", signal: "official",
          titleEn: "Japan Post official", noteEn: "The registrable domain is japanpost.jp" },
      ],
    },
  ];
})(typeof globalThis !== "undefined" ? globalThis : this);
